### ISSUE TITLE
`test` not working

### ISSUE THREAD

**Issue by mniak** [mniak/bench#14]
It should detect the program trying the following file names
- [x] `main` (PR #14)
- [x] the same name of the folder (PR #14)

with the following file extensions
- [x] `.exe` on windows (PR #14)
- [x] **(none)** on non-windows (PR #14)
- [x] `.py`
- [x] `.sh` on non-windows
- [x] `.bat` on windows
- [x] `.cmd` on windows
- [x] `.ps1` on windows
